export const playlist = [
"https://airinerra.github.io/helloword/playlist/baleylot.mp3",
"https://siskaerra.github.io/helloword/marwah/Addinu%20lana.mp3",
"https://siskaerra.github.io/helloword/marwah/Bukan%20tak%20mampu.mp3",
"https://siskaerra.github.io/helloword/marwah/Cinta%20berawan.mp3",
"https://siskaerra.github.io/helloword/marwah/Cinta%20dan%20air%20mata.mp3",
"https://siskaerra.github.io/helloword/marwah/Cinta%20hanya%20sekali.mp3",
"https://siskaerra.github.io/helloword/marwah/Cinta%20sabun%20mandi.mp3",
"https://siskaerra.github.io/helloword/marwah/Cinta%20tak%20terpisahkan.mp3",
"https://siskaerra.github.io/helloword/marwah/Citra%20cinta.mp3",
"https://siskaerra.github.io/helloword/marwah/Dadi%20siji.mp3",
"https://siskaerra.github.io/helloword/marwah/Dahlia.mp3",
"https://siskaerra.github.io/helloword/marwah/Gerigis.mp3",
"https://siskaerra.github.io/helloword/marwah/Gita%20cinta.mp3",
"https://siskaerra.github.io/helloword/marwah/Habitak.mp3",
"https://siskaerra.github.io/helloword/marwah/Jauhnya%20jarak.mp3",
"https://siskaerra.github.io/helloword/marwah/Kembang%20wangi.mp3",
"https://siskaerra.github.io/helloword/marwah/Kunanti%20di%20pintu%20surga.mp3",
"https://siskaerra.github.io/helloword/marwah/Lamunan.mp3",
"https://siskaerra.github.io/helloword/marwah/Layang%20dungo%20restu.mp3",
"https://siskaerra.github.io/helloword/marwah/Layang%20kangen.mp3",
"https://siskaerra.github.io/helloword/marwah/Lintang%20asmara.mp3",
"https://siskaerra.github.io/helloword/marwah/Madiun%20ngawi.mp3",
"https://siskaerra.github.io/helloword/marwah/Mahal.mp3",
"https://siskaerra.github.io/helloword/marwah/Mawar%20putih.mp3",
"https://siskaerra.github.io/helloword/marwah/Milikku.mp3",
"https://siskaerra.github.io/helloword/marwah/Nemen.mp3",
"https://siskaerra.github.io/helloword/marwah/Nemu.mp3",
"https://siskaerra.github.io/helloword/marwah/Ora%20iso.mp3",
"https://siskaerra.github.io/helloword/marwah/Pacobaning%20urip.mp3",
"https://siskaerra.github.io/helloword/marwah/Pelampiasan.mp3",
"https://siskaerra.github.io/helloword/marwah/Potret%20tua.mp3",
"https://siskaerra.github.io/helloword/marwah/Pujaningsih.mp3",
"https://siskaerra.github.io/helloword/marwah/Pupuse%20nelongso.mp3",
"https://siskaerra.github.io/helloword/marwah/Rasa%20tresna%20kang%20sejati.mp3",
"https://siskaerra.github.io/helloword/marwah/Rasah%20bali.mp3",
"https://siskaerra.github.io/helloword/marwah/Relaku%20mengalah.mp3",
"https://siskaerra.github.io/helloword/marwah/Rindu%20tapi%20malu.mp3",
"https://siskaerra.github.io/helloword/marwah/Salahmu%20sendiri.mp3",
"https://siskaerra.github.io/helloword/marwah/Satu%20rasa%20cinta.mp3",
"https://siskaerra.github.io/helloword/marwah/Semakin%20sayang%20semakin%20kejam.mp3",
"https://siskaerra.github.io/helloword/marwah/Sonia.mp3",
"https://siskaerra.github.io/helloword/marwah/Tajamnya%20karam.mp3",
"https://siskaerra.github.io/helloword/marwah/Talining%20asmoro.mp3",
"https://siskaerra.github.io/helloword/marwah/Taman%20curug.mp3",
"https://siskaerra.github.io/helloword/marwah/Tambal%20ban.mp3",
"https://siskaerra.github.io/helloword/marwah/Teman%20biasa.mp3",
"https://siskaerra.github.io/helloword/marwah/Teman%20sejati.mp3",
"https://siskaerra.github.io/helloword/marwah/Titip%20rogoku.mp3",
"https://siskaerra.github.io/helloword/marwah/Ungkapan%20hati.mp3",
"https://siskaerra.github.io/helloword/marwah/Ya%20asiqal%20mustofa.mp3"
];

export const titles = [
"Opening Track",
"Addinu Lana",
"Bukan tak mampu",
"Cinta Berawan",
"Cinta Dan Air Mata",
"Cinta Hanya Sekali",
"Cinta Sabun Mandi",
"Cinta Tak Terpisahkan",
"Citra Cinta",
"Dadi Siji",
"Dahlia",
"Gerigis",
"Gita Cinta",
"Habitak",
"Jauhnya Jarak",
"Kembang Wangi",
"Kunanti Dipintu Surga",
"Lamunan",
"Layang Dunga Restu",
"Layang Kangen",
"Lintang Asmara",
"Madiun Ngawi",
"Mahal",
"Mawar Putih",
"Milikku",
"Nemen",
"Nemu",
"Ora Bisa",
"Pacobaning Urip",
"Pelampiasan",
"Potret Tua",
"Pujaningsih",
"Pupuse Nelangsa",
"Rasa Tresna Kang Sejati",
"Rasah Bali",
"Relaku Mengalah",
"Rindu Tapi Malu",
"Salahmu Sendiri",
"Satu Rasa Cinta",
"Semakin Sayang Semakin Kejam",
"Sonia",
"Tajamnya Karam",
"Talining Asmara",
"Taman Curug",
"Tambal Ban",
"Teman Biasa",
"Teman Sejati",
"Titip Rogoku",
"Ungkapan Hati",
"Ya Asiqal Mustofa"
];
